// <auto-generated />
using System;
using Gadajec.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gadajec.Persistance.Migrations
{
    [DbContext(typeof(GadajecDBContext))]
    [Migration("20221019174454_RoomUser")]
    partial class RoomUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Gadajec")
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gadajec.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", "Gadajec");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e67b0cac-fea2-4a45-af7d-c3bd8c7c0229"),
                            CreatedAt = new DateTime(2022, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedBy = "Admin",
                            Name = "C# - devs"
                        },
                        new
                        {
                            Id = new Guid("f3efa56f-eb63-4d98-9200-e4af189bebd2"),
                            CreatedAt = new DateTime(2022, 10, 19, 19, 44, 53, 755, DateTimeKind.Local).AddTicks(7023),
                            CreatedBy = "Admin",
                            Name = "SQL - devs"
                        });
                });

            modelBuilder.Entity("Gadajec.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users", "Gadajec");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25b4e618-b690-4c3d-8034-c90ca11fa790"),
                            CreatedAt = new DateTime(2022, 10, 19, 19, 44, 53, 755, DateTimeKind.Local).AddTicks(6848),
                            Email = "Bartosz@mail.com.pl",
                            FirstName = "Bartosz",
                            LastName = "Bagiński",
                            Password = "SGFzbG8="
                        });
                });

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.Property<Guid>("RoomsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoomUser", "Gadajec");
                });

            modelBuilder.Entity("RoomUser", b =>
                {
                    b.HasOne("Gadajec.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gadajec.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
